// <auto-generated />
using System;
using AvicolaRenzoPredictor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AvicolaRenzoPredictor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AvicolaRenzoPredictor.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<double>("InventarioPromedio")
                        .HasColumnType("REAL");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PerdidasKg")
                        .HasColumnType("REAL");

                    b.Property<double>("PrecioKg")
                        .HasColumnType("REAL");

                    b.Property<double>("VentasKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Inventarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
